### PR TITLE
Feat/support json templates

### PR DESCRIPTION
**Pull request by rdefreitas**
RSEG contribution to allow table "templates" to be provided by a json file.
Also includes fix for Decimal data types and connection leaks on the RDD completion task.

By default, a json template will be in the same data folder as the target path with a filename of `_KINETICA.json` though this can be overridden with a configuration parameter (RSEG combines this json with other metadata being captured from their spark jobs).

### CODE REVIEW

**Comment by rdefreitas** [comment]
As a note, this enhancement is missing support for replicated tables, as it doesn't match our current use case.
If we wanted to support it, it wouldn't be a big lift - add an extra flag to the `kinetica_schema` object in the json to indicate replication and allow that to override the `table.is_replicated` property of the loader config as well as set the replicated property in the request map when creating the table

**Comment by mmahmud** [comment]
Hi Ron,

Could you please provide a sample JSON file to test this feature?

Thanks,
Meem Mahmud

**Comment by rdefreitas** [comment]
It can (and should) be generated by using the loader.
I'll enhance the `airline` tests to handle this case.

**Comment by rdefreitas** [comment]
The `avro-test` has been updated with json generated by the new components and test have been updated with examples of how to pull the schema down

**Comment by mmahmud** [comment]
Thanks!

**Comment by rdefreitas** [comment]
discovered 1 more issue with pushing back up data that was pulled down.
during egress "string|date" column becomes timestamp which when stored in avro becomes a long, either seconds or millisecond epoch depending on spark 2.3 or 2.4.
The last commit resolves this by adding options to specify either second or millisecond conversion and support casting long to a matching date column during type conversion

**Comment by rdefreitas** [comment]
@mmahmud thanks for pushing up the fix for the decimal types

**Comment by mmahmud** [comment]
Sure, no problem!  Please let me know if it works for you.

**Comment by rdefreitas** [comment]
Updated PR based on new 6.2 release branch

Here are the summarized notes on what's been changed:

- updated LoaderParams to take transient Option[SparkContext] to allow for serialization when running loader for multiple tables in parallel within a single spark job
- added necessary classes for obtaining and serializing a json representation of the type schema from Kinetica. As use of this helper is optional, it must be invoked by the user as shown in the unit tests.
- added support to kinetica loader to support the use of these templates during bulk upload to kinetica.
- during egress "string|date" column becomes a timestamp which when stored in avro becomes a long, either seconds or millisecond epoch depending on whether it's run on spark 2.3 or 2.4. We resolve this by adding options to specify either second or millisecond conversion and support casting long to a matching date column during type conversion
- during egress, allow for uploading Date columns based on a timestamp source column

**Comment by rdefreitas** [comment]
@mmahmud we've gone through the work of updating our changes to match your latest ones and have force updated the branch.

**Comment by rdefreitas** [comment]
closing this PR in favor of a new one targeting 7.0

**Pull request closed without merging**
